spring:
  application:
    name: auth-service

management:
  endpoints:
    web:
      exposure:
        include: health    

server:
  port: 8085
  servlet:
    context-path: /api/auth-service/v1

aws:
  dynamodb:
    table-name: AUTH_USER

  sns:
    order-topic-arn: arn:aws:sns:us-east-1:200849340204:order-events

jwt:
  expiration-seconds: 3600