spring:
  application:
    name: auth-service

management:
  endpoints:
    web:
      exposure:
        include: health    

server:
  port: 8085
  servlet:
    context-path: /api/auth-service/v1

aws:
  dynamodb:
    table-name: AUTH_USER